name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.1"

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "22.14"

      - name: Install dependencies
        run: |
          go mod tidy
          npm install

      - name: Run tests
        run: |
          make test

      - name: Build application
        run: |
          make build
